name = input("Enter your name")
print(name)
print(name.isalpha())
print("-" * 80)
a = input("What is 1+1")
print(a)
print(a.isnumeric())
print("-" * 80)
userid = input("Enter:")
print(userid)
print(userid.isalnum())